### ISSUE TITLE
Funcionalidade 2 - Teste

### ISSUE THREAD

**Issue by jvcaquino** [jvcaquino/DC-UFSCar-ES2-201601-Grupo6#2]
Importação de itens bibliográficos na base corrente

**Comment by falcaopetri** [comment]
Acho que é meio complicado gerar testes para a manutenção #10. Talvez poderíamos montar um grafo de fluxo de controle  (GFC) e utilizar o teste manual acompanhado de screenshots.

A manutenção #9 dá pra automatizar.
