### ISSUE TITLE
Manutenção 1 - Inserção de item bibliográfico

### ISSUE THREAD

**Issue by jvcaquino** [jvcaquino/DC-UFSCar-ES2-201601-Grupo6#3]
Na funcionalidade Inserção de item bibliográfico (BibTeX → New entry), para as categorias book e article, realizar os seguintes incrementos:

- Validar os seguintes campos de acordo com as seguintes regras:
     - Year: deve ser um ano válido (de acordo com o calendário da linguagem Java)
     - Bibtexkey: definido pelo usuário ou automaticamente, deve ter n

**Comment by falcaopetri** [comment]
O Pull Request #6 do @ThiagoYonamine valida esses dois campos. Assim que o Pull receber merge no Master, essa Issue pode ser fechada!
