### ISSUE TITLE
Manutenção 2 - Importação de itens bibliográficos

### ISSUE THREAD

**Issue by jvcaquino** [jvcaquino/DC-UFSCar-ES2-201601-Grupo6#4]
Na funcionalidade Importação de itens bibliográficos na base corrente (File → Import into current database), realizar os seguintes incrementos:

- Oferecer a opção de importar arquivo em formato CSV
- Oferecer a opção de criação de um novo arquivo (database) quando existirem entradas duplicadas no arquivo corrente (current database) e o arquivo que está sendo importado (considerar formatos BibTeX e CSV).

**Comment by falcaopetri** [comment]
Dividi essa issue em duas (#9 e #10) para organizar melhor.
