### ISSUE TITLE
Manutenção 3 - Número apenas Inteiro

### ISSUE THREAD

**Issue by jvcaquino** [jvcaquino/DC-UFSCar-ES2-201601-Grupo6#7]
Número de página sendo apenas aceito valores inteiros

**Comment by falcaopetri** [comment]
Vamos permitir intervalo de páginas? Eu sugeriria que fosse aceito um inteiro positivo, ou dois inteiros positivos separados por hífen.
Válido: 
- 5
- 456
- 1-10
- 45-50

Inválido:
- -1
- 5p
- 5 6

**Comment by jozerdj** [comment]
Permitir intervalos é legal, seria interessante nesse caso verificar se a página "final" é maior do que a página "inicial".
Poderíamos usar regex.
